name: Semgrep
on:
  pull_request: {}
  push:
    branches:
    - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
jobs:
  semgrep:
    uses: gemini/semgrep/.github/workflows/semgrep-base.yml@main
    secrets: inherit
